### ISSUE TITLE
Logger seems not to be saving logs

### ISSUE THREAD

**Issue by kauf0** [Blayung/my-plugin#2] opened 2024-02-02 10:13 UTC
I've been using Blayung's plugin for several days now and was able to witness that the BlockLogger feature doesn't write history to the 'block-log-book.txt' file.
Eventually this leads to problem that if needed to check logs, I wouldn't to. It do shows block history of changes made in current server session, but as soon as you reload it, history wipes.
<details> 
  <summary>For example </summary>
Here are two shots, in the first one there is a building I started yesterday and haven't finished yet, and it doesn't know about its history. While in the second there are block I've set some time ago during the present session.

![image](https://github.com/Blayung/my-plugin/assets/101307532/3ebf840a-b5bd-452a-8bde-2b224ea98ad1)
![image](https://github.com/Blayung/my-plugin/assets/101307532/f61aa0f7-7e6c-4cc2-bb3f-05709af09342)
</details>

**Comment by kauf0** [comment] 2024-02-02 10:29
Tried inspecting the source but at this point of my java understanding it doesn't seems vivid to me where is the problem.

**Comment by Blayung** [comment] 2024-02-02 14:13
Oh, that surely isn't expected behaviour. Since I use this plugin on my own server too, I'll check and fix it as soon as I get home. Thanks for the feedback!

**Comment by Blayung** [comment] 2024-02-02 14:15
So bad not to be home now...

**Comment by Blayung** [comment] 2024-02-02 14:15
But I'm back tomorrow!

**Comment by Blayung** [comment] 2024-02-02 14:27
And as I'm thinking about that now, I've noiticed before that the world save event is called only when stopping the server (not even on `/save-all`), and until saving it, the plugin stores all the data in ram, so calling `/reload` might fuck with it somehow. (I'm not sure how does it really work though)

**Comment by Blayung** [comment] 2024-02-02 14:30
Indeed, that doesn't sound good: https://bukkit.org/threads/what-does-reload-do.115704.

**Comment by kauf0** [comment] 2024-02-02 14:44
> And as I'm thinking about that now, I've noiticed before that the world save event is called only when stopping the server (not even on `/save-all`), and until saving it, the plugin stores all the data in ram, so calling `/reload` might fuck with it somehow. (I'm not sure how does it really work though)

I sure do /save-all every time before logging out and stopping server

**Comment by kauf0** [comment] 2024-02-02 14:51
> Indeed, that doesn't sound good: https://bukkit.org/threads/what-does-reload-do.115704.

And also on /reload, I saw lots of people assuring not to use it ever, they even have a warning message on executing this command on Paper servers at newer versions.

**Comment by Blayung** [comment] 2024-02-02 17:51
Yes, you shouldn't use reload, instead of fixing it I'll probably just put a warning not to use reload in the readme.

Does it break when simply restarting (turning off and then on) the server, or did you mean only the `/reload` command? (you didn't communicate it clearly because you've used the phrases "server session" and "reload")

**Comment by Blayung** [comment] 2024-02-02 18:04
And do you use the main branch or block-logger-item-handling-dev?

**Comment by kauf0** [comment] 2024-02-03 00:03
> Yes, you shouldn't use reload, instead of fixing it I'll probably just put a warning not to use reload in the readme.
> 
> Does it break when simply restarting (turning off and then on) the server, or did you mean only the `/reload` command? (you didn't communicate it clearly because you've used the phrases "server session" and "reload")

Alr, here's my algorithm: I never use `/reload` since it's broken, 
I always do `/save-all` and `/stop` then or simply `/stop` sometimes but none of them work in case of saving BlockLogger logs

> And do you use the main branch or block-logger-item-handling-dev?

~Main I guess(?)~ Checked twice, It's blocklogger-item-handling-dev

**Comment by Blayung** [comment] 2024-02-03 06:45
Okay, so there is definitely a big problem with saving in the blocklogger-item-handling-dev, I wanna merge it with main soon so I'm going to push the fix there.

You figured out that you need to use my build of canyon for that branch?

**Comment by Blayung** [comment] 2024-02-03 09:03
And also as I'm going home in the bus, you could try to check if the bug occurs on the main build too.

**Comment by Blayung** [comment] 2024-02-03 16:29
Okay, I've figured out it's a problem with loading, not saving.

**Comment by Blayung** [comment] 2024-02-03 17:33
Okay, I've found the problem - in blocklogger-item-handling-dev I'm no longer actually creating a BlockLogger instance, so the constructor's never called and the file is never created and the logs do not load.

The issue didn't close itself because the commit isn't on main, but I'm gonna close it with this comment. Recompile it and it'll work.

**Closed as completed by Blayung** 2024-02-03 17:33 UTC
Labels: bug
